### ISSUE TITLE
Asking for some papers or other reference materials

### ISSUE THREAD

**Issue by songzwgithub** [rbiessel/InSAR-Soil-Moisture-Model#2]
Hello, I am a graduate student from China. I'm interested in this code but can't understand it very well. Could you provide me with some reference materials, such as papers, formulas, textbooks, etc. Sorry for such a basic question. Looking forward to your reply.

**Comment by rbiessel** [comment]
Hello,

Thanks for your interest! No worries at all because this is a class project I did for an undergraduate computational physics class. What I've done is just implemented a numerical solution to the electromagnetic wave equation. It's also not optimized in a way that a solution with physical microwave frequencies is stable/can be used. Furthermore, this only considers the real part of the dielectric constant. In reality, it's the full complex part of the dielectric that is going to be important for modeling the soil moisture contribution to SAR observables.

I would check out the following papers for better more robust and meaningful models:
An analytical model from Francesco De Zan et al., 2014: https://core.ac.uk/download/pdf/31004483.pdf 
A numerical simulation from Rabus et al., 2010: https://ieeexplore.ieee.org/document/5415611

I'm also currently writing a paper on a data-driven approach to estimate soil moisture contributions based on the SAR intensity observations.

Good luck in your pursuits!

**Comment by songzwgithub** [comment]
OK, I see. Thank you very much.
